-- OMS2 SRS-aligned demo data seed
-- Idempotent: safe to rerun without duplicating seeded entities.

BEGIN;

-- Password for all seeded users: password
-- Hash generated by pgcrypto for bcrypt compatibility with backend auth.
WITH base_users(first_name, last_name, email, role_name) AS (
    VALUES
        ('Super', 'Admin', 'superadmin@oms2.local', 'super_admin'),
        ('System', 'Admin', 'admin@oms2.local', 'admin'),
        ('Project', 'Manager', 'manager@oms2.local', 'manager'),
        ('Demo', 'Employee', 'employee@oms2.local', 'user')
)
INSERT INTO users (first_name, last_name, email, password, role, is_active, created_at, updated_at, deleted_at)
SELECT
    bu.first_name,
    bu.last_name,
    bu.email,
    crypt('password', gen_salt('bf')),
    bu.role_name,
    TRUE,
    NOW() - INTERVAL '30 days',
    NOW(),
    NULL
FROM base_users bu
ON CONFLICT (email)
DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    password = EXCLUDED.password,
    role = EXCLUDED.role,
    is_active = TRUE,
    updated_at = NOW(),
    deleted_at = NULL;

WITH demo_people(idx, first_name, last_name, designation, department) AS (
    VALUES
        (1,  'Amina',  'Rahman',  'Software Engineer',      'Engineering'),
        (2,  'Fahim',  'Islam',   'QA Engineer',            'Engineering'),
