-- OMS2 SRS-aligned demo data seed
-- Idempotent: safe to rerun without duplicating seeded entities.

BEGIN;

-- Password for all seeded users: password
-- Hash generated by pgcrypto for bcrypt compatibility with backend auth.
WITH base_users(first_name, last_name, email, role_name) AS (
    VALUES
        ('Super', 'Admin', 'superadmin@oms2.local', 'super_admin'),
        ('System', 'Admin', 'admin@oms2.local', 'admin'),
        ('Project', 'Manager', 'manager@oms2.local', 'manager'),
        ('Demo', 'Employee', 'employee@oms2.local', 'user')
)
INSERT INTO users (first_name, last_name, email, password, role, is_active, created_at, updated_at, deleted_at)
SELECT
    bu.first_name,
    bu.last_name,
    bu.email,
    crypt('password', gen_salt('bf')),
    bu.role_name,
    TRUE,
    NOW() - INTERVAL '30 days',
    NOW(),
    NULL
FROM base_users bu
ON CONFLICT (email)
DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    password = EXCLUDED.password,
    role = EXCLUDED.role,
    is_active = TRUE,
    updated_at = NOW(),
    deleted_at = NULL;

WITH demo_people(idx, first_name, last_name, designation, department) AS (
    VALUES
        (1,  'Amina',  'Rahman',  'Software Engineer',      'Engineering'),
        (2,  'Fahim',  'Islam',   'QA Engineer',            'Engineering'),
        (3,  'Nabila', 'Sultana', 'Product Analyst',        'Product'),
        (4,  'Rafi',   'Hasan',   'DevOps Engineer',        'Operations'),
        (5,  'Tania',  'Kabir',   'Frontend Engineer',      'Engineering'),
        (6,  'Sabbir', 'Ahmed',   'Backend Engineer',       'Engineering'),
        (7,  'Mehjabeen','Noor',  'Project Coordinator',    'PMO'),
        (8,  'Rakib',  'Hossain', 'Business Analyst',       'Product'),
        (9,  'Shaila', 'Jahan',   'UX Designer',            'Design'),
        (10, 'Nayeem', 'Karim',   'Support Engineer',       'Operations'),
        (11, 'Farzana','Chowdhury','Data Analyst',          'Analytics'),
        (12, 'Morshed','Alam',    'Security Engineer',      'Operations'),
        (13, 'Tahsin', 'Arefin',  'Mobile Engineer',        'Engineering'),
        (14, 'Jui',    'Akter',   'Scrum Master',           'PMO'),
        (15, 'Sadia',  'Parvin',  'Technical Writer',       'Product'),
        (16, 'Nafis',  'Haque',   'Platform Engineer',      'Engineering'),
        (17, 'Elina',  'Sarker',  'QA Automation Engineer', 'Engineering'),
        (18, 'Adnan',  'Faruq',   'KPI Specialist',         'Analytics'),
        (19, 'Maliha', 'Yasmin',  'HR Associate',           'People Ops'),
        (20, 'Irfan',  'Zaman',   'Operations Executive',   'Operations')
), normalized AS (
    SELECT
        dp.idx,
        dp.first_name,
        dp.last_name,
        dp.designation,
        dp.department,
        format('demo.employee.%s@oms2.local', lpad(dp.idx::text, 2, '0')) AS email,
        format('+8801701%04s', dp.idx) AS phone,
        (CURRENT_DATE - ((dp.idx * 11) || ' days')::interval)::date AS joining_date,
        CASE WHEN dp.idx IN (19, 20) THEN 'inactive' ELSE 'active' END AS emp_status
    FROM demo_people dp
)
INSERT INTO users (first_name, last_name, email, password, role, is_active, created_at, updated_at, deleted_at)
SELECT
    n.first_name,
    n.last_name,
    n.email,
    crypt('password', gen_salt('bf')),
    'user',
    TRUE,
    NOW() - INTERVAL '20 days',
    NOW(),
    NULL
FROM normalized n
ON CONFLICT (email)
DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    password = EXCLUDED.password,
    role = EXCLUDED.role,
    is_active = TRUE,
    updated_at = NOW(),
    deleted_at = NULL;

WITH demo_people(idx, first_name, last_name, designation, department) AS (
    VALUES
        (1,  'Amina',  'Rahman',  'Software Engineer',      'Engineering'),
        (2,  'Fahim',  'Islam',   'QA Engineer',            'Engineering'),
        (3,  'Nabila', 'Sultana', 'Product Analyst',        'Product'),
        (4,  'Rafi',   'Hasan',   'DevOps Engineer',        'Operations'),
        (5,  'Tania',  'Kabir',   'Frontend Engineer',      'Engineering'),
        (6,  'Sabbir', 'Ahmed',   'Backend Engineer',       'Engineering'),
        (7,  'Mehjabeen','Noor',  'Project Coordinator',    'PMO'),
        (8,  'Rakib',  'Hossain', 'Business Analyst',       'Product'),
        (9,  'Shaila', 'Jahan',   'UX Designer',            'Design'),
        (10, 'Nayeem', 'Karim',   'Support Engineer',       'Operations'),
        (11, 'Farzana','Chowdhury','Data Analyst',          'Analytics'),
        (12, 'Morshed','Alam',    'Security Engineer',      'Operations'),
        (13, 'Tahsin', 'Arefin',  'Mobile Engineer',        'Engineering'),
        (14, 'Jui',    'Akter',   'Scrum Master',           'PMO'),
        (15, 'Sadia',  'Parvin',  'Technical Writer',       'Product'),
        (16, 'Nafis',  'Haque',   'Platform Engineer',      'Engineering'),
        (17, 'Elina',  'Sarker',  'QA Automation Engineer', 'Engineering'),
        (18, 'Adnan',  'Faruq',   'KPI Specialist',         'Analytics'),
        (19, 'Maliha', 'Yasmin',  'HR Associate',           'People Ops'),
        (20, 'Irfan',  'Zaman',   'Operations Executive',   'Operations')
), normalized AS (
    SELECT
        dp.idx,
        dp.first_name,
        dp.last_name,
        dp.designation,
        dp.department,
        format('demo.employee.%s@oms2.local', lpad(dp.idx::text, 2, '0')) AS email,
        format('+8801701%04s', dp.idx) AS phone,
        (CURRENT_DATE - ((dp.idx * 11) || ' days')::interval)::date AS joining_date,
        CASE WHEN dp.idx IN (19, 20) THEN 'inactive' ELSE 'active' END AS emp_status
    FROM demo_people dp
)
INSERT INTO employees (first_name, last_name, email, phone, designation, department, joining_date, status, created_at, updated_at, deleted_at)
SELECT
    n.first_name,
    n.last_name,
    n.email,
    n.phone,
    n.designation,
    n.department,
    n.joining_date,
    n.emp_status,
    NOW() - INTERVAL '20 days',
    NOW(),
    NULL
FROM normalized n
ON CONFLICT (email)
DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    phone = EXCLUDED.phone,
    designation = EXCLUDED.designation,
    department = EXCLUDED.department,
    joining_date = EXCLUDED.joining_date,
    status = EXCLUDED.status,
    updated_at = NOW(),
    deleted_at = NULL;

WITH demo_projects(project_name, short_description, start_date, end_date, status_name, project_type) AS (
    VALUES
        ('OMS2 Platform Revamp', 'Modernize project operations UI, workflows, and reporting integration.', CURRENT_DATE - INTERVAL '70 days', CURRENT_DATE + INTERVAL '120 days', 'Active', 'Internal'),
        ('Client Onboarding Portal', 'Deliver structured onboarding lifecycle for enterprise clients.', CURRENT_DATE - INTERVAL '45 days', CURRENT_DATE + INTERVAL '95 days', 'Active', 'Client'),
        ('RAG KPI Insights Rollout', 'Operationalize retrieval, wiki regeneration, and KPI visibility.', CURRENT_DATE - INTERVAL '55 days', CURRENT_DATE + INTERVAL '110 days', 'Active', 'R&D'),
        ('Mobile Timesheet Pilot', 'Pilot mobile-first timesheet capture for distributed field teams.', CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE + INTERVAL '75 days', 'On Hold', 'Internal'),
        ('Internal Automation Hub', 'Centralize automation patterns and process optimization initiatives.', CURRENT_DATE - INTERVAL '90 days', CURRENT_DATE + INTERVAL '40 days', 'Completed', 'Internal')
)
INSERT INTO projects (name, short_description, start_date, end_date, status, type, created_at, updated_at, deleted_at)
SELECT
    dp.project_name,
    dp.short_description,
    dp.start_date,
    dp.end_date,
    dp.status_name,
    dp.project_type,
    NOW() - INTERVAL '25 days',
    NOW(),
    NULL
FROM demo_projects dp
ON CONFLICT (name)
DO UPDATE SET
    short_description = EXCLUDED.short_description,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    status = EXCLUDED.status,
    type = EXCLUDED.type,
    updated_at = NOW(),
    deleted_at = NULL;

WITH role_seed(project_name, email, role_name) AS (
    VALUES
        ('OMS2 Platform Revamp', 'superadmin@oms2.local', 'owner'),
        ('OMS2 Platform Revamp', 'admin@oms2.local', 'editor'),
        ('OMS2 Platform Revamp', 'manager@oms2.local', 'editor'),
        ('OMS2 Platform Revamp', 'demo.employee.01@oms2.local', 'viewer'),
        ('OMS2 Platform Revamp', 'demo.employee.02@oms2.local', 'viewer'),
        ('OMS2 Platform Revamp', 'demo.employee.03@oms2.local', 'viewer'),
        ('Client Onboarding Portal', 'admin@oms2.local', 'owner'),
        ('Client Onboarding Portal', 'manager@oms2.local', 'editor'),
        ('Client Onboarding Portal', 'demo.employee.04@oms2.local', 'viewer'),
        ('Client Onboarding Portal', 'demo.employee.05@oms2.local', 'viewer'),
        ('Client Onboarding Portal', 'demo.employee.06@oms2.local', 'viewer'),
        ('RAG KPI Insights Rollout', 'superadmin@oms2.local', 'owner'),
        ('RAG KPI Insights Rollout', 'demo.employee.07@oms2.local', 'editor'),
        ('RAG KPI Insights Rollout', 'demo.employee.08@oms2.local', 'viewer'),
        ('RAG KPI Insights Rollout', 'demo.employee.09@oms2.local', 'viewer'),
        ('Mobile Timesheet Pilot', 'manager@oms2.local', 'owner'),
        ('Mobile Timesheet Pilot', 'demo.employee.10@oms2.local', 'editor'),
        ('Mobile Timesheet Pilot', 'demo.employee.11@oms2.local', 'viewer'),
        ('Internal Automation Hub', 'admin@oms2.local', 'owner'),
        ('Internal Automation Hub', 'demo.employee.12@oms2.local', 'editor'),
        ('Internal Automation Hub', 'demo.employee.13@oms2.local', 'viewer')
), resolved AS (
    SELECT
        p.id AS project_id,
        u.id AS user_id,
        rs.role_name
    FROM role_seed rs
    JOIN projects p ON p.name = rs.project_name AND p.deleted_at IS NULL
    JOIN users u ON u.email = rs.email AND u.deleted_at IS NULL
)
UPDATE project_roles pr
SET
    role = r.role_name,
    updated_at = NOW(),
    deleted_at = NULL
FROM resolved r
WHERE pr.project_id = r.project_id
  AND pr.user_id = r.user_id;

WITH role_seed(project_name, email, role_name) AS (
    VALUES
        ('OMS2 Platform Revamp', 'superadmin@oms2.local', 'owner'),
        ('OMS2 Platform Revamp', 'admin@oms2.local', 'editor'),
        ('OMS2 Platform Revamp', 'manager@oms2.local', 'editor'),
        ('OMS2 Platform Revamp', 'demo.employee.01@oms2.local', 'viewer'),
        ('OMS2 Platform Revamp', 'demo.employee.02@oms2.local', 'viewer'),
        ('OMS2 Platform Revamp', 'demo.employee.03@oms2.local', 'viewer'),
        ('Client Onboarding Portal', 'admin@oms2.local', 'owner'),
        ('Client Onboarding Portal', 'manager@oms2.local', 'editor'),
        ('Client Onboarding Portal', 'demo.employee.04@oms2.local', 'viewer'),
        ('Client Onboarding Portal', 'demo.employee.05@oms2.local', 'viewer'),
        ('Client Onboarding Portal', 'demo.employee.06@oms2.local', 'viewer'),
        ('RAG KPI Insights Rollout', 'superadmin@oms2.local', 'owner'),
        ('RAG KPI Insights Rollout', 'demo.employee.07@oms2.local', 'editor'),
        ('RAG KPI Insights Rollout', 'demo.employee.08@oms2.local', 'viewer'),
        ('RAG KPI Insights Rollout', 'demo.employee.09@oms2.local', 'viewer'),
        ('Mobile Timesheet Pilot', 'manager@oms2.local', 'owner'),
        ('Mobile Timesheet Pilot', 'demo.employee.10@oms2.local', 'editor'),
        ('Mobile Timesheet Pilot', 'demo.employee.11@oms2.local', 'viewer'),
        ('Internal Automation Hub', 'admin@oms2.local', 'owner'),
        ('Internal Automation Hub', 'demo.employee.12@oms2.local', 'editor'),
        ('Internal Automation Hub', 'demo.employee.13@oms2.local', 'viewer')
), resolved AS (
    SELECT
        p.id AS project_id,
        u.id AS user_id,
        rs.role_name
    FROM role_seed rs
    JOIN projects p ON p.name = rs.project_name AND p.deleted_at IS NULL
    JOIN users u ON u.email = rs.email AND u.deleted_at IS NULL
)
INSERT INTO project_roles (user_id, project_id, role, created_at, updated_at, deleted_at)
SELECT
    r.user_id,
    r.project_id,
    r.role_name,
    NOW(),
    NOW(),
    NULL
FROM resolved r
WHERE NOT EXISTS (
    SELECT 1
    FROM project_roles pr
    WHERE pr.user_id = r.user_id
      AND pr.project_id = r.project_id
);

WITH task_seed(project_name, title, description, status_name, assignee_email, deadline_days, started_days, completed_days) AS (
    VALUES
        ('OMS2 Platform Revamp', 'Backlog grooming for Q2 epics', 'Prepare prioritized backlog and acceptance criteria for Q2 epics.', 'To Do', 'demo.employee.01@oms2.local', 8, 0, 0),
        ('OMS2 Platform Revamp', 'Implement role-based sidebar navigation', 'Deliver role-aware workspace navigation and permissions mapping.', 'In Progress', 'demo.employee.02@oms2.local', 6, 4, 0),
        ('OMS2 Platform Revamp', 'Migrate dashboard KPIs to API contracts', 'Replace static KPI metrics with backend-driven summaries.', 'Done', 'demo.employee.03@oms2.local', -2, 9, 2),
        ('OMS2 Platform Revamp', 'Stabilize task status transition audit logs', 'Ensure every status transition writes a traceable audit entry.', 'In Progress', 'demo.employee.04@oms2.local', 9, 3, 0),
        ('OMS2 Platform Revamp', 'Build attendance analytics widgets', 'Add attendance scorecards and distribution metrics for managers.', 'To Do', 'demo.employee.05@oms2.local', 11, 0, 0),
