-- OMS2 SRS-aligned demo data seed
-- Idempotent: safe to rerun without duplicating seeded entities.

BEGIN;

-- Password for all seeded users: password
-- Hash generated by pgcrypto for bcrypt compatibility with backend auth.
WITH base_users(first_name, last_name, email, role_name) AS (
    VALUES
        ('Super', 'Admin', 'superadmin@oms2.local', 'super_admin'),
        ('System', 'Admin', 'admin@oms2.local', 'admin'),
        ('Project', 'Manager', 'manager@oms2.local', 'manager'),
        ('Demo', 'Employee', 'employee@oms2.local', 'user')
)
INSERT INTO users (first_name, last_name, email, password, role, is_active, created_at, updated_at, deleted_at)
SELECT
    bu.first_name,
    bu.last_name,
    bu.email,
    crypt('password', gen_salt('bf')),
    bu.role_name,
    TRUE,
    NOW() - INTERVAL '30 days',
    NOW(),
    NULL
FROM base_users bu
ON CONFLICT (email)
DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    password = EXCLUDED.password,
    role = EXCLUDED.role,
    is_active = TRUE,
    updated_at = NOW(),
    deleted_at = NULL;

WITH demo_people(idx, first_name, last_name, designation, department) AS (
    VALUES
        (1,  'Amina',  'Rahman',  'Software Engineer',      'Engineering'),
        (2,  'Fahim',  'Islam',   'QA Engineer',            'Engineering'),
        (3,  'Nabila', 'Sultana', 'Product Analyst',        'Product'),
        (4,  'Rafi',   'Hasan',   'DevOps Engineer',        'Operations'),
        (5,  'Tania',  'Kabir',   'Frontend Engineer',      'Engineering'),
        (6,  'Sabbir', 'Ahmed',   'Backend Engineer',       'Engineering'),
        (7,  'Mehjabeen','Noor',  'Project Coordinator',    'PMO'),
        (8,  'Rakib',  'Hossain', 'Business Analyst',       'Product'),
        (9,  'Shaila', 'Jahan',   'UX Designer',            'Design'),
        (10, 'Nayeem', 'Karim',   'Support Engineer',       'Operations'),
        (11, 'Farzana','Chowdhury','Data Analyst',          'Analytics'),
        (12, 'Morshed','Alam',    'Security Engineer',      'Operations'),
        (13, 'Tahsin', 'Arefin',  'Mobile Engineer',        'Engineering'),
        (14, 'Jui',    'Akter',   'Scrum Master',           'PMO'),
        (15, 'Sadia',  'Parvin',  'Technical Writer',       'Product'),
        (16, 'Nafis',  'Haque',   'Platform Engineer',      'Engineering'),
        (17, 'Elina',  'Sarker',  'QA Automation Engineer', 'Engineering'),
        (18, 'Adnan',  'Faruq',   'KPI Specialist',         'Analytics'),
        (19, 'Maliha', 'Yasmin',  'HR Associate',           'People Ops'),
        (20, 'Irfan',  'Zaman',   'Operations Executive',   'Operations')
), normalized AS (
    SELECT
        dp.idx,
        dp.first_name,
        dp.last_name,
        dp.designation,
        dp.department,
        format('demo.employee.%s@oms2.local', lpad(dp.idx::text, 2, '0')) AS email,
        format('+8801701%04s', dp.idx) AS phone,
        (CURRENT_DATE - ((dp.idx * 11) || ' days')::interval)::date AS joining_date,
        CASE WHEN dp.idx IN (19, 20) THEN 'inactive' ELSE 'active' END AS emp_status
    FROM demo_people dp
)
INSERT INTO users (first_name, last_name, email, password, role, is_active, created_at, updated_at, deleted_at)
SELECT
    n.first_name,
    n.last_name,
    n.email,
    crypt('password', gen_salt('bf')),
    'user',
    TRUE,
    NOW() - INTERVAL '20 days',
    NOW(),
    NULL
FROM normalized n
ON CONFLICT (email)
DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    password = EXCLUDED.password,
    role = EXCLUDED.role,
    is_active = TRUE,
    updated_at = NOW(),
    deleted_at = NULL;

WITH demo_people(idx, first_name, last_name, designation, department) AS (
    VALUES
        (1,  'Amina',  'Rahman',  'Software Engineer',      'Engineering'),
        (2,  'Fahim',  'Islam',   'QA Engineer',            'Engineering'),
        (3,  'Nabila', 'Sultana', 'Product Analyst',        'Product'),
        (4,  'Rafi',   'Hasan',   'DevOps Engineer',        'Operations'),
        (5,  'Tania',  'Kabir',   'Frontend Engineer',      'Engineering'),
        (6,  'Sabbir', 'Ahmed',   'Backend Engineer',       'Engineering'),
        (7,  'Mehjabeen','Noor',  'Project Coordinator',    'PMO'),
        (8,  'Rakib',  'Hossain', 'Business Analyst',       'Product'),
        (9,  'Shaila', 'Jahan',   'UX Designer',            'Design'),
        (10, 'Nayeem', 'Karim',   'Support Engineer',       'Operations'),
        (11, 'Farzana','Chowdhury','Data Analyst',          'Analytics'),
        (12, 'Morshed','Alam',    'Security Engineer',      'Operations'),
        (13, 'Tahsin', 'Arefin',  'Mobile Engineer',        'Engineering'),
        (14, 'Jui',    'Akter',   'Scrum Master',           'PMO'),
        (15, 'Sadia',  'Parvin',  'Technical Writer',       'Product'),
        (16, 'Nafis',  'Haque',   'Platform Engineer',      'Engineering'),
        (17, 'Elina',  'Sarker',  'QA Automation Engineer', 'Engineering'),
        (18, 'Adnan',  'Faruq',   'KPI Specialist',         'Analytics'),
        (19, 'Maliha', 'Yasmin',  'HR Associate',           'People Ops'),
        (20, 'Irfan',  'Zaman',   'Operations Executive',   'Operations')
), normalized AS (
    SELECT
        dp.idx,
        dp.first_name,
        dp.last_name,
        dp.designation,
        dp.department,
        format('demo.employee.%s@oms2.local', lpad(dp.idx::text, 2, '0')) AS email,
        format('+8801701%04s', dp.idx) AS phone,
        (CURRENT_DATE - ((dp.idx * 11) || ' days')::interval)::date AS joining_date,
        CASE WHEN dp.idx IN (19, 20) THEN 'inactive' ELSE 'active' END AS emp_status
    FROM demo_people dp
)
INSERT INTO employees (first_name, last_name, email, phone, designation, department, joining_date, status, created_at, updated_at, deleted_at)
SELECT
    n.first_name,
    n.last_name,
    n.email,
    n.phone,
    n.designation,
    n.department,
    n.joining_date,
    n.emp_status,
    NOW() - INTERVAL '20 days',
    NOW(),
    NULL
FROM normalized n
ON CONFLICT (email)
DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    phone = EXCLUDED.phone,
    designation = EXCLUDED.designation,
    department = EXCLUDED.department,
    joining_date = EXCLUDED.joining_date,
    status = EXCLUDED.status,
    updated_at = NOW(),
    deleted_at = NULL;

WITH demo_projects(project_name, short_description, start_date, end_date, status_name, project_type) AS (
    VALUES
        ('OMS2 Platform Revamp', 'Modernize project operations UI, workflows, and reporting integration.', CURRENT_DATE - INTERVAL '70 days', CURRENT_DATE + INTERVAL '120 days', 'Active', 'Internal'),
        ('Client Onboarding Portal', 'Deliver structured onboarding lifecycle for enterprise clients.', CURRENT_DATE - INTERVAL '45 days', CURRENT_DATE + INTERVAL '95 days', 'Active', 'Client'),
        ('RAG KPI Insights Rollout', 'Operationalize retrieval, wiki regeneration, and KPI visibility.', CURRENT_DATE - INTERVAL '55 days', CURRENT_DATE + INTERVAL '110 days', 'Active', 'R&D'),
        ('Mobile Timesheet Pilot', 'Pilot mobile-first timesheet capture for distributed field teams.', CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE + INTERVAL '75 days', 'On Hold', 'Internal'),
        ('Internal Automation Hub', 'Centralize automation patterns and process optimization initiatives.', CURRENT_DATE - INTERVAL '90 days', CURRENT_DATE + INTERVAL '40 days', 'Completed', 'Internal')
)
INSERT INTO projects (name, short_description, start_date, end_date, status, type, created_at, updated_at, deleted_at)
SELECT
    dp.project_name,
    dp.short_description,
    dp.start_date,
    dp.end_date,
    dp.status_name,
    dp.project_type,
    NOW() - INTERVAL '25 days',
    NOW(),
    NULL
FROM demo_projects dp
ON CONFLICT (name)
DO UPDATE SET
    short_description = EXCLUDED.short_description,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    status = EXCLUDED.status,
    type = EXCLUDED.type,
    updated_at = NOW(),
    deleted_at = NULL;

WITH role_seed(project_name, email, role_name) AS (
    VALUES
        ('OMS2 Platform Revamp', 'superadmin@oms2.local', 'owner'),
        ('OMS2 Platform Revamp', 'admin@oms2.local', 'editor'),
        ('OMS2 Platform Revamp', 'manager@oms2.local', 'editor'),
        ('OMS2 Platform Revamp', 'demo.employee.01@oms2.local', 'viewer'),
        ('OMS2 Platform Revamp', 'demo.employee.02@oms2.local', 'viewer'),
        ('OMS2 Platform Revamp', 'demo.employee.03@oms2.local', 'viewer'),
        ('Client Onboarding Portal', 'admin@oms2.local', 'owner'),
        ('Client Onboarding Portal', 'manager@oms2.local', 'editor'),
        ('Client Onboarding Portal', 'demo.employee.04@oms2.local', 'viewer'),
        ('Client Onboarding Portal', 'demo.employee.05@oms2.local', 'viewer'),
        ('Client Onboarding Portal', 'demo.employee.06@oms2.local', 'viewer'),
        ('RAG KPI Insights Rollout', 'superadmin@oms2.local', 'owner'),
        ('RAG KPI Insights Rollout', 'demo.employee.07@oms2.local', 'editor'),
        ('RAG KPI Insights Rollout', 'demo.employee.08@oms2.local', 'viewer'),
        ('RAG KPI Insights Rollout', 'demo.employee.09@oms2.local', 'viewer'),
        ('Mobile Timesheet Pilot', 'manager@oms2.local', 'owner'),
        ('Mobile Timesheet Pilot', 'demo.employee.10@oms2.local', 'editor'),
        ('Mobile Timesheet Pilot', 'demo.employee.11@oms2.local', 'viewer'),
        ('Internal Automation Hub', 'admin@oms2.local', 'owner'),
        ('Internal Automation Hub', 'demo.employee.12@oms2.local', 'editor'),
        ('Internal Automation Hub', 'demo.employee.13@oms2.local', 'viewer')
), resolved AS (
    SELECT
        p.id AS project_id,
        u.id AS user_id,
        rs.role_name
    FROM role_seed rs
    JOIN projects p ON p.name = rs.project_name AND p.deleted_at IS NULL
    JOIN users u ON u.email = rs.email AND u.deleted_at IS NULL
)
UPDATE project_roles pr
SET
    role = r.role_name,
    updated_at = NOW(),
    deleted_at = NULL
FROM resolved r
WHERE pr.project_id = r.project_id
  AND pr.user_id = r.user_id;

WITH role_seed(project_name, email, role_name) AS (
    VALUES
        ('OMS2 Platform Revamp', 'superadmin@oms2.local', 'owner'),
        ('OMS2 Platform Revamp', 'admin@oms2.local', 'editor'),
        ('OMS2 Platform Revamp', 'manager@oms2.local', 'editor'),
        ('OMS2 Platform Revamp', 'demo.employee.01@oms2.local', 'viewer'),
        ('OMS2 Platform Revamp', 'demo.employee.02@oms2.local', 'viewer'),
        ('OMS2 Platform Revamp', 'demo.employee.03@oms2.local', 'viewer'),
        ('Client Onboarding Portal', 'admin@oms2.local', 'owner'),
        ('Client Onboarding Portal', 'manager@oms2.local', 'editor'),
        ('Client Onboarding Portal', 'demo.employee.04@oms2.local', 'viewer'),
        ('Client Onboarding Portal', 'demo.employee.05@oms2.local', 'viewer'),
        ('Client Onboarding Portal', 'demo.employee.06@oms2.local', 'viewer'),
        ('RAG KPI Insights Rollout', 'superadmin@oms2.local', 'owner'),
        ('RAG KPI Insights Rollout', 'demo.employee.07@oms2.local', 'editor'),
        ('RAG KPI Insights Rollout', 'demo.employee.08@oms2.local', 'viewer'),
        ('RAG KPI Insights Rollout', 'demo.employee.09@oms2.local', 'viewer'),
        ('Mobile Timesheet Pilot', 'manager@oms2.local', 'owner'),
        ('Mobile Timesheet Pilot', 'demo.employee.10@oms2.local', 'editor'),
        ('Mobile Timesheet Pilot', 'demo.employee.11@oms2.local', 'viewer'),
        ('Internal Automation Hub', 'admin@oms2.local', 'owner'),
        ('Internal Automation Hub', 'demo.employee.12@oms2.local', 'editor'),
        ('Internal Automation Hub', 'demo.employee.13@oms2.local', 'viewer')
), resolved AS (
    SELECT
        p.id AS project_id,
        u.id AS user_id,
        rs.role_name
    FROM role_seed rs
    JOIN projects p ON p.name = rs.project_name AND p.deleted_at IS NULL
    JOIN users u ON u.email = rs.email AND u.deleted_at IS NULL
)
INSERT INTO project_roles (user_id, project_id, role, created_at, updated_at, deleted_at)
SELECT
    r.user_id,
    r.project_id,
    r.role_name,
    NOW(),
    NOW(),
    NULL
FROM resolved r
WHERE NOT EXISTS (
    SELECT 1
    FROM project_roles pr
    WHERE pr.user_id = r.user_id
      AND pr.project_id = r.project_id
);

WITH task_seed(project_name, title, description, status_name, assignee_email, deadline_days, started_days, completed_days) AS (
    VALUES
        ('OMS2 Platform Revamp', 'Backlog grooming for Q2 epics', 'Prepare prioritized backlog and acceptance criteria for Q2 epics.', 'To Do', 'demo.employee.01@oms2.local', 8, 0, 0),
        ('OMS2 Platform Revamp', 'Implement role-based sidebar navigation', 'Deliver role-aware workspace navigation and permissions mapping.', 'In Progress', 'demo.employee.02@oms2.local', 6, 4, 0),
        ('OMS2 Platform Revamp', 'Migrate dashboard KPIs to API contracts', 'Replace static KPI metrics with backend-driven summaries.', 'Done', 'demo.employee.03@oms2.local', -2, 9, 2),
        ('OMS2 Platform Revamp', 'Stabilize task status transition audit logs', 'Ensure every status transition writes a traceable audit entry.', 'In Progress', 'demo.employee.04@oms2.local', 9, 3, 0),
        ('OMS2 Platform Revamp', 'Build attendance analytics widgets', 'Add attendance scorecards and distribution metrics for managers.', 'To Do', 'demo.employee.05@oms2.local', 11, 0, 0),
        ('OMS2 Platform Revamp', 'Write regression suite for auth flows', 'Automate login/session/logout regression checks.', 'Done', 'demo.employee.06@oms2.local', -1, 7, 1),

        ('Client Onboarding Portal', 'Design onboarding checklist workflow', 'Create onboarding stage definitions and handoff criteria.', 'To Do', 'demo.employee.07@oms2.local', 10, 0, 0),
        ('Client Onboarding Portal', 'Integrate client profile approval service', 'Wire approvals into profile activation and risk checks.', 'In Progress', 'demo.employee.08@oms2.local', 7, 3, 0),
        ('Client Onboarding Portal', 'Create welcome email automation templates', 'Finalize email templates and trigger events for launch.', 'Done', 'demo.employee.09@oms2.local', -3, 10, 3),
        ('Client Onboarding Portal', 'Configure SLA escalation matrix', 'Define incident escalations and breach response ownership.', 'In Progress', 'demo.employee.10@oms2.local', 5, 2, 0),
        ('Client Onboarding Portal', 'Build document upload policy validation', 'Add policy checks for document format and compliance rules.', 'To Do', 'demo.employee.11@oms2.local', 12, 0, 0),
        ('Client Onboarding Portal', 'Demo dry-run with mock tenant', 'Run end-to-end onboarding rehearsal with demo data.', 'Done', 'demo.employee.12@oms2.local', -1, 8, 1),

        ('RAG KPI Insights Rollout', 'Index historical updates for retrieval', 'Backfill chunk index with historical project updates.', 'In Progress', 'demo.employee.13@oms2.local', 6, 5, 0),
        ('RAG KPI Insights Rollout', 'Implement semantic wiki regeneration job', 'Regenerate project wiki from retrieved context snapshots.', 'To Do', 'demo.employee.14@oms2.local', 9, 0, 0),
        ('RAG KPI Insights Rollout', 'Expose KPI trend endpoint for leadership', 'Publish trend metrics endpoint for executive dashboard.', 'Done', 'demo.employee.15@oms2.local', -4, 9, 2),
        ('RAG KPI Insights Rollout', 'Add cache invalidation for stale sources', 'Invalidate search cache when source freshness window expires.', 'In Progress', 'demo.employee.16@oms2.local', 4, 2, 0),
        ('RAG KPI Insights Rollout', 'Tune vector search threshold per project', 'Calibrate threshold values to improve retrieval precision.', 'To Do', 'demo.employee.17@oms2.local', 11, 0, 0),
        ('RAG KPI Insights Rollout', 'Publish RAG governance audit dashboard', 'Expose ingestion, retrieval, and model-governance visibility.', 'Done', 'demo.employee.18@oms2.local', -2, 7, 1),

        ('Mobile Timesheet Pilot', 'Define mobile submission API contract', 'Document and review contract for mobile timesheet submissions.', 'To Do', 'demo.employee.01@oms2.local', 13, 0, 0),
        ('Mobile Timesheet Pilot', 'Build offline queue synchronization logic', 'Sync local mobile drafts to server with conflict handling.', 'In Progress', 'demo.employee.02@oms2.local', 9, 3, 0),
        ('Mobile Timesheet Pilot', 'QA pass for timezone-aware timestamps', 'Verify timezone-safe creation and reporting of entries.', 'Done', 'demo.employee.03@oms2.local', -1, 8, 1),
        ('Mobile Timesheet Pilot', 'Add push reminder scheduling pipeline', 'Schedule configurable reminder pushes for missing entries.', 'In Progress', 'demo.employee.04@oms2.local', 6, 2, 0),
        ('Mobile Timesheet Pilot', 'Pilot rollout checklist for field teams', 'Prepare rollout tasks and ownership matrix for pilot teams.', 'To Do', 'demo.employee.05@oms2.local', 15, 0, 0),
        ('Mobile Timesheet Pilot', 'Capture pilot retrospective findings', 'Summarize pilot outcomes, blockers, and next iterations.', 'Done', 'demo.employee.06@oms2.local', -1, 7, 1),

        ('Internal Automation Hub', 'Map repetitive ops workflows for automation', 'Identify repeatable service-desk workflows for automation.', 'To Do', 'demo.employee.07@oms2.local', 8, 0, 0),
        ('Internal Automation Hub', 'Implement workflow bot for ticket triage', 'Build rule-driven triage bot and confidence scoring.', 'In Progress', 'demo.employee.08@oms2.local', 5, 3, 0),
        ('Internal Automation Hub', 'Deliver no-code automation playbook v1', 'Publish no-code automation patterns and implementation guides.', 'Done', 'demo.employee.09@oms2.local', -3, 10, 2),
        ('Internal Automation Hub', 'Add failure alerting for automation jobs', 'Create alerting, escalation, and recovery hooks for job failures.', 'In Progress', 'demo.employee.10@oms2.local', 7, 4, 0),
        ('Internal Automation Hub', 'Train support team on runbook updates', 'Run training sessions and adoption tracking for support team.', 'To Do', 'demo.employee.11@oms2.local', 10, 0, 0),
        ('Internal Automation Hub', 'Executive review with ROI summary', 'Present ROI outcomes and scaling recommendations.', 'Done', 'demo.employee.12@oms2.local', -2, 9, 2)
), resolved AS (
    SELECT
        p.id AS project_id,
        ts.title,
        ts.description,
        ts.status_name,
        e.id AS assignee_id,
        ts.deadline_days,
        ts.started_days,
        ts.completed_days
    FROM task_seed ts
    JOIN projects p ON p.name = ts.project_name AND p.deleted_at IS NULL
    JOIN employees e ON e.email = ts.assignee_email AND e.deleted_at IS NULL
)
UPDATE tasks t
SET
    description = r.description,
    deadline = (CURRENT_DATE + (r.deadline_days || ' days')::interval),
    status = r.status_name,
    assignee_id = r.assignee_id,
    updated_at = NOW(),
    started_at = CASE
        WHEN r.status_name IN ('In Progress', 'Done') THEN COALESCE(t.started_at, NOW() - (r.started_days || ' days')::interval)
        ELSE NULL
    END,
    completed_at = CASE
        WHEN r.status_name = 'Done' THEN COALESCE(t.completed_at, NOW() - (r.completed_days || ' days')::interval)
        ELSE NULL
    END
FROM resolved r
WHERE t.project_id = r.project_id
  AND t.title = r.title;

WITH task_seed(project_name, title, description, status_name, assignee_email, deadline_days, started_days, completed_days) AS (
    VALUES
        ('OMS2 Platform Revamp', 'Backlog grooming for Q2 epics', 'Prepare prioritized backlog and acceptance criteria for Q2 epics.', 'To Do', 'demo.employee.01@oms2.local', 8, 0, 0),
        ('OMS2 Platform Revamp', 'Implement role-based sidebar navigation', 'Deliver role-aware workspace navigation and permissions mapping.', 'In Progress', 'demo.employee.02@oms2.local', 6, 4, 0),
        ('OMS2 Platform Revamp', 'Migrate dashboard KPIs to API contracts', 'Replace static KPI metrics with backend-driven summaries.', 'Done', 'demo.employee.03@oms2.local', -2, 9, 2),
        ('OMS2 Platform Revamp', 'Stabilize task status transition audit logs', 'Ensure every status transition writes a traceable audit entry.', 'In Progress', 'demo.employee.04@oms2.local', 9, 3, 0),
        ('OMS2 Platform Revamp', 'Build attendance analytics widgets', 'Add attendance scorecards and distribution metrics for managers.', 'To Do', 'demo.employee.05@oms2.local', 11, 0, 0),
        ('OMS2 Platform Revamp', 'Write regression suite for auth flows', 'Automate login/session/logout regression checks.', 'Done', 'demo.employee.06@oms2.local', -1, 7, 1),

        ('Client Onboarding Portal', 'Design onboarding checklist workflow', 'Create onboarding stage definitions and handoff criteria.', 'To Do', 'demo.employee.07@oms2.local', 10, 0, 0),
        ('Client Onboarding Portal', 'Integrate client profile approval service', 'Wire approvals into profile activation and risk checks.', 'In Progress', 'demo.employee.08@oms2.local', 7, 3, 0),
        ('Client Onboarding Portal', 'Create welcome email automation templates', 'Finalize email templates and trigger events for launch.', 'Done', 'demo.employee.09@oms2.local', -3, 10, 3),
        ('Client Onboarding Portal', 'Configure SLA escalation matrix', 'Define incident escalations and breach response ownership.', 'In Progress', 'demo.employee.10@oms2.local', 5, 2, 0),
        ('Client Onboarding Portal', 'Build document upload policy validation', 'Add policy checks for document format and compliance rules.', 'To Do', 'demo.employee.11@oms2.local', 12, 0, 0),
        ('Client Onboarding Portal', 'Demo dry-run with mock tenant', 'Run end-to-end onboarding rehearsal with demo data.', 'Done', 'demo.employee.12@oms2.local', -1, 8, 1),

        ('RAG KPI Insights Rollout', 'Index historical updates for retrieval', 'Backfill chunk index with historical project updates.', 'In Progress', 'demo.employee.13@oms2.local', 6, 5, 0),
        ('RAG KPI Insights Rollout', 'Implement semantic wiki regeneration job', 'Regenerate project wiki from retrieved context snapshots.', 'To Do', 'demo.employee.14@oms2.local', 9, 0, 0),
        ('RAG KPI Insights Rollout', 'Expose KPI trend endpoint for leadership', 'Publish trend metrics endpoint for executive dashboard.', 'Done', 'demo.employee.15@oms2.local', -4, 9, 2),
        ('RAG KPI Insights Rollout', 'Add cache invalidation for stale sources', 'Invalidate search cache when source freshness window expires.', 'In Progress', 'demo.employee.16@oms2.local', 4, 2, 0),
        ('RAG KPI Insights Rollout', 'Tune vector search threshold per project', 'Calibrate threshold values to improve retrieval precision.', 'To Do', 'demo.employee.17@oms2.local', 11, 0, 0),
        ('RAG KPI Insights Rollout', 'Publish RAG governance audit dashboard', 'Expose ingestion, retrieval, and model-governance visibility.', 'Done', 'demo.employee.18@oms2.local', -2, 7, 1),

        ('Mobile Timesheet Pilot', 'Define mobile submission API contract', 'Document and review contract for mobile timesheet submissions.', 'To Do', 'demo.employee.01@oms2.local', 13, 0, 0),
        ('Mobile Timesheet Pilot', 'Build offline queue synchronization logic', 'Sync local mobile drafts to server with conflict handling.', 'In Progress', 'demo.employee.02@oms2.local', 9, 3, 0),
        ('Mobile Timesheet Pilot', 'QA pass for timezone-aware timestamps', 'Verify timezone-safe creation and reporting of entries.', 'Done', 'demo.employee.03@oms2.local', -1, 8, 1),
        ('Mobile Timesheet Pilot', 'Add push reminder scheduling pipeline', 'Schedule configurable reminder pushes for missing entries.', 'In Progress', 'demo.employee.04@oms2.local', 6, 2, 0),
        ('Mobile Timesheet Pilot', 'Pilot rollout checklist for field teams', 'Prepare rollout tasks and ownership matrix for pilot teams.', 'To Do', 'demo.employee.05@oms2.local', 15, 0, 0),
        ('Mobile Timesheet Pilot', 'Capture pilot retrospective findings', 'Summarize pilot outcomes, blockers, and next iterations.', 'Done', 'demo.employee.06@oms2.local', -1, 7, 1),

        ('Internal Automation Hub', 'Map repetitive ops workflows for automation', 'Identify repeatable service-desk workflows for automation.', 'To Do', 'demo.employee.07@oms2.local', 8, 0, 0),
        ('Internal Automation Hub', 'Implement workflow bot for ticket triage', 'Build rule-driven triage bot and confidence scoring.', 'In Progress', 'demo.employee.08@oms2.local', 5, 3, 0),
        ('Internal Automation Hub', 'Deliver no-code automation playbook v1', 'Publish no-code automation patterns and implementation guides.', 'Done', 'demo.employee.09@oms2.local', -3, 10, 2),
        ('Internal Automation Hub', 'Add failure alerting for automation jobs', 'Create alerting, escalation, and recovery hooks for job failures.', 'In Progress', 'demo.employee.10@oms2.local', 7, 4, 0),
        ('Internal Automation Hub', 'Train support team on runbook updates', 'Run training sessions and adoption tracking for support team.', 'To Do', 'demo.employee.11@oms2.local', 10, 0, 0),
        ('Internal Automation Hub', 'Executive review with ROI summary', 'Present ROI outcomes and scaling recommendations.', 'Done', 'demo.employee.12@oms2.local', -2, 9, 2)
), resolved AS (
    SELECT
        p.id AS project_id,
        ts.title,
        ts.description,
        ts.status_name,
        e.id AS assignee_id,
        ts.deadline_days,
        ts.started_days,
        ts.completed_days
    FROM task_seed ts
    JOIN projects p ON p.name = ts.project_name AND p.deleted_at IS NULL
    JOIN employees e ON e.email = ts.assignee_email AND e.deleted_at IS NULL
)
INSERT INTO tasks (project_id, title, description, deadline, status, assignee_id, created_at, updated_at, started_at, completed_at)
SELECT
    r.project_id,
    r.title,
    r.description,
    (CURRENT_DATE + (r.deadline_days || ' days')::interval),
    r.status_name,
    r.assignee_id,
    NOW() - ((r.started_days + 12) || ' days')::interval,
    NOW(),
    CASE
        WHEN r.status_name IN ('In Progress', 'Done') THEN NOW() - (r.started_days || ' days')::interval
        ELSE NULL
    END,
    CASE
        WHEN r.status_name = 'Done' THEN NOW() - (r.completed_days || ' days')::interval
        ELSE NULL
    END
FROM resolved r
WHERE NOT EXISTS (
    SELECT 1
    FROM tasks t
    WHERE t.project_id = r.project_id
      AND t.title = r.title
);

WITH seeded_tasks AS (
    SELECT t.id, t.title, t.status, t.assignee_id, t.created_at, t.started_at, t.completed_at
    FROM tasks t
    WHERE t.title IN (
        'Backlog grooming for Q2 epics',
        'Implement role-based sidebar navigation',
        'Migrate dashboard KPIs to API contracts',
        'Stabilize task status transition audit logs',
        'Build attendance analytics widgets',
        'Write regression suite for auth flows',
        'Design onboarding checklist workflow',
        'Integrate client profile approval service',
        'Create welcome email automation templates',
        'Configure SLA escalation matrix',
        'Build document upload policy validation',
        'Demo dry-run with mock tenant',
        'Index historical updates for retrieval',
        'Implement semantic wiki regeneration job',
        'Expose KPI trend endpoint for leadership',
        'Add cache invalidation for stale sources',
        'Tune vector search threshold per project',
        'Publish RAG governance audit dashboard',
        'Define mobile submission API contract',
        'Build offline queue synchronization logic',
        'QA pass for timezone-aware timestamps',
        'Add push reminder scheduling pipeline',
        'Pilot rollout checklist for field teams',
        'Capture pilot retrospective findings',
        'Map repetitive ops workflows for automation',
        'Implement workflow bot for ticket triage',
        'Deliver no-code automation playbook v1',
        'Add failure alerting for automation jobs',
        'Train support team on runbook updates',
        'Executive review with ROI summary'
    )
), assignees AS (
    SELECT
        st.id AS task_id,
        COALESCE(u.id, (SELECT id FROM users WHERE email = 'admin@oms2.local' LIMIT 1)) AS changed_by,
        st.status,
        st.created_at,
        st.started_at,
        st.completed_at
    FROM seeded_tasks st
    LEFT JOIN employees e ON e.id = st.assignee_id
    LEFT JOIN users u ON u.email = e.email
)
INSERT INTO task_status_logs (task_id, from_status, to_status, changed_by, comment, created_at)
SELECT
    a.task_id,
    NULL,
    'To Do',
    a.changed_by,
    'seeded task created',
    COALESCE(a.created_at, NOW() - INTERVAL '14 days')
FROM assignees a
WHERE NOT EXISTS (
    SELECT 1
    FROM task_status_logs l
    WHERE l.task_id = a.task_id
      AND l.from_status IS NULL
      AND l.to_status = 'To Do'
);

WITH seeded_tasks AS (
    SELECT t.id, t.status, t.assignee_id, t.created_at, t.started_at
    FROM tasks t
    WHERE t.title IN (
        'Backlog grooming for Q2 epics',
        'Implement role-based sidebar navigation',
        'Migrate dashboard KPIs to API contracts',
        'Stabilize task status transition audit logs',
        'Build attendance analytics widgets',
        'Write regression suite for auth flows',
        'Design onboarding checklist workflow',
        'Integrate client profile approval service',
        'Create welcome email automation templates',
        'Configure SLA escalation matrix',
        'Build document upload policy validation',
        'Demo dry-run with mock tenant',
        'Index historical updates for retrieval',
        'Implement semantic wiki regeneration job',
